/**
 * Adds a double-clickable ApplyPilot icon:  npm run shortcut
 *
 *   Windows  "ApplyPilot" on the desktop and in the Start menu
 *   macOS    ApplyPilot.app on the desktop
 *   Linux    an ApplyPilot launcher on the desktop and in the applications menu
 *
 * The icon runs the same thing as `npm run launch`: it opens a terminal
 * window with the server in it (close the window to stop ApplyPilot) and opens
 * the app in the browser. `npm run launch` creates the icon on its first run;
 * run this again after moving the project folder.
 *
 * Plain JavaScript with only Node built-ins, like launch.mjs, because it runs
 * before dependencies are installed.
 */

import { spawnSync } from "node:child_process";
import { chmodSync, copyFileSync, existsSync, mkdirSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";

const NAME = "ApplyPilot";
const DESCRIPTION = "ApplyPilot - AI job applications";

/** Quotes a value for a POSIX shell: it's -> 'it'\''s'. */
export function shellQuote(value) {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Quotes one argument of a .desktop Exec line. The spec applies its quoting
 * rule first and general string escaping second, so backslashes end up doubled
 * twice; `%` is doubled because it introduces field codes.
 */
export function desktopExecArg(value) {
  const quoted = `"${value.replace(/[\\"`$]/g, (char) => `\\${char}`)}"`;
  return quoted.replace(/\\/g, "\\\\").replace(/%/g, "%%");
}

function desktopString(value) {
  return value.replace(/\\/g, "\\\\").replace(/\n/g, "\\n");
}

/** The script the macOS and Linux icons run. */
export function posixLauncher({ projectDir, nodeBin }) {
  return `#!/bin/sh
# Starts ApplyPilot. Generated by scripts/shortcut.mjs - run \`npm run shortcut\`
# again if the project folder moves.

# The Node.js that set this up comes first; the login shell's PATH is the fallback.
PATH=${shellQuote(nodeBin)}:"$PATH"
export PATH
cd ${shellQuote(projectDir)} || exit 1
node scripts/launch.mjs
status=$?
if [ "$status" -ne 0 ]; then
  printf '\\nApplyPilot stopped with an error. Press Enter to close this window.'
  read -r _
fi
exit "$status"
`;
}

export function desktopEntry({ exec, icon }) {
  return [
    "[Desktop Entry]",
    "Type=Application",
    "Version=1.0",
    `Name=${NAME}`,
    `Comment=${DESCRIPTION}`,
    `Exec=${desktopExecArg(exec)}`,
    `Icon=${desktopString(icon)}`,
    "Terminal=true",
    "Categories=Office;",
    "",
  ].join("\n");
}

export function infoPlist() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${NAME}</string>
  <key>CFBundleDisplayName</key><string>${NAME}</string>
  <key>CFBundleIdentifier</key><string>com.applypilot.launcher</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>${NAME}</string>
  <key>CFBundleIconFile</key><string>applypilot</string>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
</dict>
</plist>
`;
}

/**
 * The .app's executable. It hands the launcher to Terminal rather than running
 * it directly: apps started from Finder get a bare PATH without Node, and the
 * Terminal window doubles as the "app is running" indicator.
 */
export function macAppExecutable() {
  return `#!/bin/sh
exec open -a Terminal "$(dirname "$0")/../Resources/launch.command"
`;
}

/**
 * PowerShell that writes the .lnk files. Paths arrive in environment
 * variables, so no quoting of user paths is involved.
 */
export function windowsShortcutScript() {
  return [
    "$ErrorActionPreference = 'Stop'",
    "$shell = New-Object -ComObject WScript.Shell",
    // Resolved by Windows, so OneDrive-redirected desktops work too.
    "foreach ($folder in @('Desktop', 'Programs')) {",
    "  $dir = [Environment]::GetFolderPath($folder)",
    "  if (-not $dir) { continue }",
    "  $path = Join-Path $dir 'ApplyPilot.lnk'",
    "  $link = $shell.CreateShortcut($path)",
    "  $link.TargetPath = $env:APPLYPILOT_TARGET",
    "  $link.WorkingDirectory = $env:APPLYPILOT_DIR",
    "  $link.IconLocation = $env:APPLYPILOT_ICON + ',0'",
    "  $link.Description = $env:APPLYPILOT_DESCRIPTION",
    "  $link.Save()",
    "  Write-Output $path",
    "}",
  ].join("\n");
}

function writeExecutable(file, content) {
  writeFileSync(file, content);
  chmodSync(file, 0o755);
}

function createWindowsShortcuts(projectDir) {
  const script = windowsShortcutScript();
  const result = spawnSync(
    "powershell.exe",
    [
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-EncodedCommand",
      Buffer.from(script, "utf16le").toString("base64"),
    ],
    {
      encoding: "utf8",
      env: {
        ...process.env,
        APPLYPILOT_TARGET: path.join(projectDir, "start-windows.cmd"),
        APPLYPILOT_DIR: projectDir,
        APPLYPILOT_ICON: path.join(projectDir, "assets", "applypilot.ico"),
        APPLYPILOT_DESCRIPTION: DESCRIPTION,
      },
    },
  );
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(result.stderr.trim().split(/\r?\n/)[0] || `PowerShell exited with code ${result.status}`);
  }
  return result.stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function createMacApp(projectDir, nodeBin) {
  const desktop = path.join(homedir(), "Desktop");
  const app = path.join(desktop, `${NAME}.app`);
  const contents = path.join(app, "Contents");

  rmSync(app, { recursive: true, force: true });
  mkdirSync(path.join(contents, "MacOS"), { recursive: true });
  mkdirSync(path.join(contents, "Resources"), { recursive: true });
  writeFileSync(path.join(contents, "Info.plist"), infoPlist());
  writeExecutable(path.join(contents, "MacOS", NAME), macAppExecutable());
  // Generated here rather than shipped in the repo: files created locally
  // carry no quarantine flag, so Gatekeeper does not block the icon.
  writeExecutable(path.join(contents, "Resources", "launch.command"), posixLauncher({ projectDir, nodeBin }));
  copyFileSync(path.join(projectDir, "assets", "applypilot.icns"), path.join(contents, "Resources", "applypilot.icns"));

  // A fresh modification time makes Finder pick up the icon straight away.
  const now = new Date();
  utimesSync(app, now, now);
  return [app];
}

function linuxDesktopDir() {
  const xdg = spawnSync("xdg-user-dir", ["DESKTOP"], { encoding: "utf8" });
  const fromXdg = xdg.status === 0 ? xdg.stdout.trim() : "";
  // xdg-user-dir answers with $HOME when no desktop folder is configured.
  const candidate = fromXdg && fromXdg !== homedir() ? fromXdg : path.join(homedir(), "Desktop");
  return existsSync(candidate) ? candidate : null;
}

function createLinuxLaunchers(projectDir, nodeBin) {
  const dataDir = process.env.XDG_DATA_HOME || path.join(homedir(), ".local", "share");
  const script = path.join(dataDir, "applypilot", "launch.sh");
  mkdirSync(path.dirname(script), { recursive: true });
  writeExecutable(script, posixLauncher({ projectDir, nodeBin }));

  const entry = desktopEntry({ exec: script, icon: path.join(projectDir, "assets", "applypilot.png") });
  const created = [];

  const desktop = linuxDesktopDir();
  if (desktop) {
    const file = path.join(desktop, "applypilot.desktop");
    writeExecutable(file, entry);
    // GNOME only runs desktop launchers marked as trusted.
    spawnSync("gio", ["set", file, "metadata::trusted", "true"], { stdio: "ignore" });
    created.push(file);
  }

  const menuEntry = path.join(dataDir, "applications", "applypilot.desktop");
  mkdirSync(path.dirname(menuEntry), { recursive: true });
  writeExecutable(menuEntry, entry);
  created.push(menuEntry);
  return created;
}

/** Creates the icon(s) for this platform and returns the paths written. */
export function createShortcut(projectDir = process.cwd()) {
  const dir = path.resolve(projectDir);
  const nodeBin = path.dirname(process.execPath);
  if (process.platform === "win32") return createWindowsShortcuts(dir);
  if (process.platform === "darwin") return createMacApp(dir, nodeBin);
  return createLinuxLaunchers(dir, nodeBin);
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    const created = createShortcut();
    console.log(`ApplyPilot icon added:\n${created.map((file) => `  ${file}`).join("\n")}`);
  } catch (error) {
    console.error(`Could not add the ApplyPilot icon: ${error instanceof Error ? error.message : error}`);
    process.exit(1);
  }
}
